version: 2

sources:
  - name: musicbrainz
    schema: main
    tables:
      - name: raw_musicbrainz_labels
        description: "Raw JSON ingest of MusicBrainz labels"

  - name: spotify_enrichment
    schema: main
    description: "Tables populated by Python enrichment scripts (outside dbt)"
    tables:
      - name: dim_track_metadata
        description: "Track/artist label info enriched from Spotify API"